# Generated by Django 4.2.7 on 2026-04-21 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create_user', 'Create User'), ('update_user', 'Update User'), ('deactivate_user', 'Deactivate User'), ('delete_user', 'Delete User'), ('login', 'User Login'), ('logout', 'User Logout'), ('failed_login', 'Failed Login'), ('account_locked', 'Account Locked'), ('account_unlocked', 'Account Unlocked'), ('password_reset', 'Password Reset'), ('create_appointment', 'Create Appointment'), ('update_appointment', 'Update Appointment'), ('cancel_appointment', 'Cancel Appointment'), ('reschedule_appointment', 'Reschedule Appointment'), ('complete_appointment', 'Complete Appointment'), ('mark_no_show', 'Mark No-Show'), ('create_availability', 'Create Availability'), ('update_availability', 'Update Availability'), ('delete_availability', 'Delete Availability'), ('create_blocked_period', 'Create Blocked Period'), ('update_blocked_period', 'Update Blocked Period'), ('delete_blocked_period', 'Delete Blocked Period'), ('generate_report', 'Generate Report'), ('export_data', 'Export Data'), ('system_config', 'System Configuration')], max_length=30)),
                ('target_user', models.CharField(blank=True, max_length=150)),
                ('target_object', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
